# Generated by Django 4.1.3 on 2023-12-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_artist_song_count_alter_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='songgenre',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='songgenre',
            old_name='song',
            new_name='song_id',
        ),
    ]
